import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { useAuth } from "@/lib/auth";
import { configuredEndpoint } from "@/lib/api";
import { BrandMark, PrimaryButton, colors } from "@/components/talentlens-ui";

export default function LoginScreen() {
  const { signIn, register } = useAuth();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [role, setRole] = useState<"recruiter" | "candidate">("recruiter"); const [registering, setRegistering] = useState(false); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!email.trim() || !password) { Alert.alert("Check your details", "Enter both an email address and password."); return; } if (registering && !name.trim()) { Alert.alert("Check your details", "Enter your name to create an account."); return; } setBusy(true); try { if (registering) await register(name.trim(), email.trim(), password, role); else await signIn(email.trim(), password); router.replace("/(tabs)"); } catch (error) { Alert.alert("TalentLens sign-in", error instanceof Error ? error.message : "Unable to sign in."); } finally { setBusy(false); } };
  return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.page}><View style={styles.editorial}><View><View style={styles.brandRow}><BrandMark /><Text style={styles.brand}>TALENTLENS</Text></View><Text style={styles.index}>MOBILE ACCESS</Text><Text style={styles.hero}>Recruitment has more signal than noise.</Text><Text style={styles.editorialCopy}>Carry the structured recruiting workspace into every hiring conversation.</Text></View><View style={styles.redSquare} /><Text style={styles.editorialFoot}>Set a secure API address in EXPO_PUBLIC_TALENTLENS_API_URL to connect this app to your live TalentLens backend.</Text></View><View style={styles.formPanel}><Text style={styles.kicker}>{registering ? "CREATE ACCOUNT" : "WELCOME BACK"}</Text><Text style={styles.formTitle}>{registering ? "Set up your workspace." : "Sign in to TalentLens."}</Text><Text style={styles.formCopy}>{registering ? "Choose the workspace role that reflects how you will use TalentLens." : "Use your credentials from the TalentLens website."}</Text>{!configuredEndpoint() && <View style={styles.endpointNotice}><Text style={styles.endpointText}>Backend address is not configured yet. The screens are ready; set EXPO_PUBLIC_TALENTLENS_API_URL before live sign-in.</Text></View>}{registering && <><Text style={styles.label}>FULL NAME</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Your name" autoCapitalize="words" /><Text style={styles.label}>WORKSPACE ROLE</Text><View style={styles.roleRow}>{(["recruiter", "candidate"] as const).map((item) => <Pressable key={item} onPress={() => setRole(item)} style={[styles.roleButton, role === item && styles.roleButtonActive]}><Text style={[styles.roleText, role === item && styles.roleTextActive]}>{item === "recruiter" ? "Recruiter" : "Candidate"}</Text></Pressable>)}</View></>}<Text style={styles.label}>EMAIL ADDRESS</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} placeholder="name@company.com" autoCapitalize="none" keyboardType="email-address" /><Text style={styles.label}>PASSWORD</Text><TextInput style={styles.input} value={password} onChangeText={setPassword} placeholder="••••••••" secureTextEntry /><PrimaryButton label={busy ? "Working…" : registering ? "Create account" : "Sign in"} onPress={submit} disabled={busy} /><Pressable onPress={() => setRegistering((value) => !value)} style={styles.switch}><Text style={styles.switchText}>{registering ? "Already have an account? Sign in" : "New to TalentLens? Create a profile"}</Text></Pressable></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, editorial: { flex: 1, minHeight: 310, backgroundColor: colors.ink, padding: 28, justifyContent: "space-between", overflow: "hidden" }, brandRow: { flexDirection: "row", alignItems: "center", gap: 10 }, brand: { color: "white", fontWeight: "900", letterSpacing: -0.6, fontSize: 14 }, index: { color: colors.red, fontFamily: "SpaceMono", fontSize: 9, letterSpacing: 1, marginTop: 35 }, hero: { color: "white", fontSize: 39, fontWeight: "900", letterSpacing: -2.5, lineHeight: 39, marginTop: 10, maxWidth: 315 }, editorialCopy: { color: "#C5C5BE", fontSize: 12, lineHeight: 18, marginTop: 12, maxWidth: 300 }, redSquare: { position: "absolute", width: 150, height: 150, backgroundColor: colors.red, bottom: -50, right: -30 }, editorialFoot: { color: "#C5C5BE", fontSize: 10, lineHeight: 15, maxWidth: 275 }, formPanel: { flex: 1.2, padding: 28, justifyContent: "center" }, kicker: { color: colors.muted, fontFamily: "SpaceMono", fontSize: 9, letterSpacing: 1 }, formTitle: { color: colors.ink, fontSize: 30, fontWeight: "900", letterSpacing: -1.8, marginTop: 8 }, formCopy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 7, marginBottom: 18 }, label: { color: colors.ink, fontFamily: "SpaceMono", fontSize: 9, letterSpacing: 0.8, marginTop: 12, marginBottom: 6 }, input: { borderWidth: 1, borderColor: colors.line, height: 44, paddingHorizontal: 11, color: colors.ink, fontSize: 13 }, endpointNotice: { backgroundColor: colors.redSoft, borderWidth: 1, borderColor: colors.line, padding: 10, marginBottom: 4 }, endpointText: { color: colors.ink, fontSize: 10, lineHeight: 15 }, roleRow: { flexDirection: "row", borderWidth: 1, borderColor: colors.line }, roleButton: { flex: 1, alignItems: "center", paddingVertical: 10 }, roleButtonActive: { backgroundColor: colors.ink }, roleText: { color: colors.muted, fontWeight: "800", fontSize: 11 }, roleTextActive: { color: "white" }, switch: { alignItems: "center", paddingTop: 18 }, switchText: { color: colors.red, fontSize: 11, fontWeight: "800" } });
