import * as DocumentPicker from "expo-document-picker";
import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useAuth } from "@/lib/auth";
import { mobileApi } from "@/lib/api";
import { PrimaryButton, colors } from "@/components/talentlens-ui";

export default function UploadScreen() { const { token } = useAuth(); const [file, setFile] = useState<DocumentPicker.DocumentPickerAsset | null>(null); const [busy, setBusy] = useState(false); const choose = async () => { const result = await DocumentPicker.getDocumentAsync({ type: "application/pdf", copyToCacheDirectory: true }); if (!result.canceled) setFile(result.assets[0]); }; const upload = async () => { if (!token || !file) return; setBusy(true); try { await mobileApi.uploadResume(token, file.uri, file.name, file.mimeType || "application/pdf"); Alert.alert("Resume uploaded", "TalentLens has started parsing your profile.", [{ text: "Done", onPress: () => router.back() }]); } catch (e) { Alert.alert("Unable to upload", e instanceof Error ? e.message : "Try again later."); } finally { setBusy(false); } }; return <View style={styles.screen}><Text style={styles.index}>RESUME UPLOAD</Text><Text style={styles.title}>Bring your work into focus.</Text><Text style={styles.copy}>Select a PDF resume from your Android device. TalentLens will send it to the existing parsing pipeline in the web backend.</Text><Pressable onPress={choose} style={({ pressed }) => [styles.dropzone, pressed && { opacity: 0.78 }]}><Text style={styles.dropTitle}>{file ? file.name : "Select a PDF resume"}</Text><Text style={styles.dropCopy}>{file ? `${Math.max(1, Math.round((file.size ?? 0) / 1024))} KB · ready to upload` : "Choose a file from your device"}</Text><Text style={styles.dropMeta}>PDF ONLY · MAXIMUM 10 MB</Text></Pressable>{file && <PrimaryButton label={busy ? "Uploading…" : "Upload and parse resume"} onPress={upload} disabled={busy} />}<Pressable onPress={() => router.back()} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper, padding: 22, paddingTop: 54 }, index: { color: colors.red, fontFamily: "SpaceMono", fontSize: 9, letterSpacing: 1 }, title: { color: colors.ink, fontSize: 34, fontWeight: "900", lineHeight: 34, letterSpacing: -2, marginTop: 8 }, copy: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 12 }, dropzone: { minHeight: 250, marginVertical: 28, borderWidth: 1, borderStyle: "dashed", borderColor: colors.line, alignItems: "center", justifyContent: "center", padding: 22 }, dropTitle: { color: colors.ink, fontSize: 19, fontWeight: "900", letterSpacing: -0.8, textAlign: "center" }, dropCopy: { color: colors.muted, fontSize: 11, marginTop: 8, textAlign: "center" }, dropMeta: { color: colors.muted, fontFamily: "SpaceMono", fontSize: 9, letterSpacing: 0.6, marginTop: 18 }, cancel: { alignItems: "center", padding: 17 }, cancelText: { color: colors.muted, fontFamily: "SpaceMono", fontSize: 10 } });
