import { useCallback, useEffect, useState } from "react";
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useAuth } from "@/lib/auth";
import { mobileApi, type MobileJob } from "@/lib/api";
import { EmptyState, LoadingState, PrimaryButton, ScreenTitle, StatusPill, colors } from "@/components/talentlens-ui";

export default function JobsScreen() { const { token, user } = useAuth(); const [jobs, setJobs] = useState<MobileJob[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const load = useCallback(async () => { if (!token) return; try { setError(null); setJobs(await mobileApi.jobs(token)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load jobs."); } finally { setLoading(false); setRefreshing(false); } }, [token]); useEffect(() => { load(); }, [load]); const apply = async (job: MobileJob) => { if (!token) return; try { await mobileApi.apply(token, job.id); Alert.alert("Application submitted", `Your profile is now connected to ${job.title}.`); load(); } catch (e) { Alert.alert("Unable to apply", e instanceof Error ? e.message : "Try again from the web workspace."); } }; if (loading) return <LoadingState label="Loading roles…" />; return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} tintColor={colors.red} />}><ScreenTitle index="02 / JOBS" title={user?.role === "candidate" ? "Open roles, without the noise." : "Every role. One decision surface."} description={user?.role === "candidate" ? "Browse roles that are live in the TalentLens hiring workspace." : "Review live roles and move directly into explainable candidate ranking."} action={user?.role === "candidate" ? undefined : <PrimaryButton label="Manage on web" onPress={() => Alert.alert("Web workspace", "Create and edit roles in the TalentLens web workspace.")} />} />{error ? <EmptyState title="Backend connection needed" detail={error} /> : jobs.length ? jobs.map((job) => <View key={job.id} style={styles.card}><View style={styles.cardTop}><StatusPill status="SHORTLISTED" /><Text style={styles.domain}>{job.domain || "GENERAL"}</Text></View><Text style={styles.jobTitle}>{job.title}</Text><Text style={styles.jobMeta}>{job.company || "TalentLens client"}{job.department ? ` · ${job.department}` : ""}</Text><View style={styles.details}><Text><Text style={styles.detailStrong}>{job.experienceYears}</Text> years required</Text><Text><Text style={styles.detailStrong}>{job.educationLevel || "Any"}</Text> education</Text></View>{user?.role === "candidate" ? <PrimaryButton label={job.applied ? "Applied" : "Apply to this role"} onPress={() => apply(job)} disabled={Boolean(job.applied)} /> : <Pressable onPress={() => router.push("/(tabs)/rankings")}><Text style={styles.open}>Open ranking</Text></Pressable>}</View>) : <EmptyState title="No open jobs" detail="Create a job on the TalentLens website, then refresh this mobile workspace." />}</ScrollView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { padding: 18, gap: 0, paddingBottom: 36 }, card: { borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 22 }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, domain: { color: colors.muted, fontFamily: "SpaceMono", fontSize: 9, letterSpacing: 0.8 }, jobTitle: { color: colors.ink, fontSize: 25, lineHeight: 26, fontWeight: "900", letterSpacing: -1.5, marginTop: 24 }, jobMeta: { color: colors.muted, fontSize: 12, marginTop: 7 }, details: { flexDirection: "row", gap: 20, marginTop: 22, marginBottom: 17 }, detailStrong: { color: colors.ink, fontWeight: "900" }, open: { color: colors.ink, fontSize: 12, fontWeight: "800", borderTopWidth: 1, borderColor: colors.line, paddingTop: 12 } });
