"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useSession } from "next-auth/react";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, BriefcaseBusiness, Check, Download, GraduationCap, Mail, MapPin, Save, Sparkles } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";

type Skill = { id: string; name: string; proficiency: string; durationMonths: number };
type Education = { id: string; institution: string; degree: string; fieldOfStudy: string; startYear: number | null; endYear: number | null; tier: string };
type CareerHistory = { id: string; company: string; title: string; startDate: string | null; endDate: string | null; durationMonths: number; isCurrent: boolean; description: string | null };
type Match = { id: string; jobId: string; overallScore: number; semanticSimilarity: number; skillMatchScore: number; experienceScore: number; educationScore: number; availabilityScore: number; strengths: string[]; weaknesses: string[]; missingSkills: string[]; hiringRecommendation: string; improvementSuggestions: string[]; recruiterNotes: string | null; recruiterStatus: string; job: { id: string; title: string; company: string | null } };
type Candidate = { id: string; candidateId: string; name: string; headline: string | null; summary: string | null; rawResumeText: string; location: string | null; country: string | null; currentTitle: string | null; currentCompany: string | null; yearsOfExperience: number; skills: Skill[]; education: Education[]; careerHistory: CareerHistory[]; matches: Match[] };
const percent = (value: number) => Math.round(value <= 1 ? value * 100 : value);
const apiStatus = (label: string) => label === "Shortlist" ? "SHORTLISTED" : label === "Reject" ? "REJECTED" : "PENDING";
const displayStatus = (value: string) => value === "SHORTLISTED" ? "Shortlist" : value === "REJECTED" ? "Reject" : "Pending";

export default function CandidateProfilePage() {
  const params = useParams<{ candidateId: string }>();
  const { data: session } = useSession();
  const role = (session?.user as { role?: string } | undefined)?.role || "recruiter";
  const [candidate, setCandidate] = useState<Candidate | null>(null);
  const [activeMatchId, setActiveMatchId] = useState("");
  const [notes, setNotes] = useState("");
  const [status, setStatus] = useState("PENDING");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => { const id = params.candidateId; if (!id) return; fetch(`/api/candidates/${id}`).then(async (response) => { if (!response.ok) throw new Error("Candidate profile not found."); return response.json() as Promise<Candidate>; }).then((nextCandidate) => { setCandidate(nextCandidate); const firstMatch = nextCandidate.matches[0]; if (firstMatch) { setActiveMatchId(firstMatch.id); setNotes(firstMatch.recruiterNotes || ""); setStatus(firstMatch.recruiterStatus); } }).catch((err: unknown) => setError(err instanceof Error ? err.message : "Candidate profile not found.")).finally(() => setLoading(false)); }, [params.candidateId]);
  const activeMatch = useMemo(() => candidate?.matches.find((match) => match.id === activeMatchId), [candidate, activeMatchId]);
  const selectMatch = (id: string) => { const next = candidate?.matches.find((match) => match.id === id); if (!next) return; setActiveMatchId(id); setNotes(next.recruiterNotes || ""); setStatus(next.recruiterStatus); };
  const saveDecision = async () => { if (!activeMatch) return; setSaving(true); try { const response = await fetch(`/api/matches/${activeMatch.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recruiterStatus: status, recruiterNotes: notes }) }); if (!response.ok) throw new Error("Unable to save recruiter decision."); setCandidate((current) => current ? { ...current, matches: current.matches.map((match) => match.id === activeMatch.id ? { ...match, recruiterStatus: status, recruiterNotes: notes } : match) } : current); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to save recruiter decision."); } finally { setSaving(false); } };
  const downloadResume = () => { if (!candidate) return; const url = URL.createObjectURL(new Blob([candidate.rawResumeText], { type: "text/plain" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${candidate.name.replace(/\s+/g, "_")}_extracted_resume.txt`; anchor.click(); URL.revokeObjectURL(url); };
  if (loading) return <DashboardLayout><div className="p-12 text-center text-sm text-[var(--muted)]">Loading candidate evidence…</div></DashboardLayout>;
  if (!candidate) return <DashboardLayout><div className="border border-[var(--line)] bg-[#fff0ec] p-8 text-sm">{error || "Candidate profile not found."}</div></DashboardLayout>;
  const activeScores = activeMatch ? [["semantic", activeMatch.semanticSimilarity], ["skills", activeMatch.skillMatchScore], ["experience", activeMatch.experienceScore], ["education", activeMatch.educationScore], ["availability", activeMatch.availabilityScore]] : [];
  const initials = candidate.name.split(" ").map((part) => part[0]).join("").slice(0, 2);
  return <DashboardLayout><button className="tl-back" onClick={() => history.back()}><ArrowLeft size={14} />All candidates</button><section className="tl-candidate-hero"><div className="tl-candidate-identity"><span>{initials}</span><div><p className="tl-eyebrow">CANDIDATE / {candidate.candidateId.slice(0, 7).toUpperCase()}</p><h1>{candidate.name}</h1><p>{candidate.currentTitle || candidate.headline || "Candidate profile"}{candidate.currentCompany ? ` · ${candidate.currentCompany}` : ""}</p><div className="tl-contact-line"><span><Mail size={13} />Verified profile</span><span><MapPin size={13} />{candidate.location || candidate.country || "Location not shared"}</span></div></div></div><div className="tl-candidate-score"><p className="tl-micro">BEST MATCH</p><strong>{activeMatch ? percent(activeMatch.overallScore) : "—"}</strong><span>{activeMatch?.job.title || "No active match"}</span></div></section>
    <section className="tl-data-grid"><article className="tl-panel"><p className="tl-micro">PROFILE SUMMARY</p><h2 className="tl-profile-heading">{candidate.currentTitle || "Candidate"} with a clear evidence trail.</h2><p className="tl-profile-copy">{candidate.summary || "This profile was built from the candidate’s submitted resume and structured work history."}</p><div className="mt-5 flex flex-wrap gap-1.5">{candidate.skills.slice(0, 8).map((skill) => <span className="tl-skill" key={skill.id}>{skill.name}</span>)}</div></article><article className="tl-panel"><p className="tl-micro">MATCH BREAKDOWN</p>{activeScores.length ? <div className="mt-5 space-y-3">{activeScores.map(([label, value]) => <div className="tl-score-line" key={String(label)}><span>{label}</span><div><i style={{ width: `${percent(Number(value))}%` }} /></div><b>{percent(Number(value))}</b></div>)}</div> : <p className="mt-5 text-sm text-[var(--muted)]">No matching score is available yet.</p>}</article></section>
    <section className="tl-data-grid"><article className="tl-panel"><div className="tl-panel-header"><div><p className="tl-micro">CAREER HISTORY</p><h2 className="tl-panel-title">Selected experience</h2></div><BriefcaseBusiness size={19} /></div><div className="mt-6 space-y-5">{candidate.careerHistory.map((career) => <div className="tl-career" key={career.id}><i /><div><p className="tl-micro">{career.startDate ? new Date(career.startDate).getFullYear() : "—"} — {career.isCurrent ? "Present" : career.endDate ? new Date(career.endDate).getFullYear() : "—"}</p><strong>{career.title}</strong><span>{career.company}</span>{career.description && <p>{career.description}</p>}</div></div>)}</div></article><article className="tl-panel"><div className="tl-panel-header"><div><p className="tl-micro">EDUCATION</p><h2 className="tl-panel-title">Foundation</h2></div><GraduationCap size={19} /></div><div className="mt-6 space-y-3">{candidate.education.map((education) => <div className="tl-education" key={education.id}><span>{education.startYear || "—"} — {education.endYear || "—"}</span><strong>{education.degree}</strong><p>{education.institution}</p><small>{education.fieldOfStudy}{education.tier ? ` · ${education.tier}` : ""}</small></div>)}</div></article></section>
    {role !== "candidate" && <section className="tl-decision-panel"><div><p className="tl-micro">RECRUITER DECISION</p><h2 className="tl-panel-title">Keep the judgment visible.</h2><select value={activeMatchId} onChange={(event) => selectMatch(event.target.value)}>{candidate.matches.map((match) => <option key={match.id} value={match.id}>{match.job.title}</option>)}</select></div>{activeMatch ? <div className="tl-decision-grid"><section><p className="tl-micro">AI RECOMMENDATION</p><p className="tl-recommendation">{activeMatch.hiringRecommendation || "Review the score and evidence before moving the candidate forward."}</p><p className="tl-micro mt-5">STRENGTHS</p>{activeMatch.strengths.slice(0, 4).map((item) => <p className="tl-tick" key={item}><Check size={14} />{item}</p>)}</section><section><p className="tl-micro">IMPROVEMENT SUGGESTIONS</p><div className="tl-suggestion"><Sparkles size={16} /><p>{activeMatch.improvementSuggestions[0] || "Use the interview to validate the score dimensions that need more evidence."}</p></div><p className="tl-micro mt-5">RECRUITER STATUS</p><div className="tl-status-controls">{["Shortlist", "Reject", "Pending"].map((label) => <button key={label} className={displayStatus(status) === label ? "is-selected" : ""} onClick={() => setStatus(apiStatus(label))}>{label}</button>)}</div><textarea className="tl-notes" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Add private recruiter notes…" /><button className="tl-red-button mt-3" onClick={saveDecision} disabled={saving}>{saving ? "Saving…" : "Save decision"}<Save size={15} /></button></section></div> : <p className="mt-5 text-sm text-[var(--muted)]">This candidate is not linked to a job match yet.</p>}</section>}
    <button className="tl-link mt-6 inline-flex items-center gap-2" onClick={downloadResume}><Download size={15} />Download extracted resume text</button>{error && <p className="mt-3 text-sm text-[var(--coral)]"><AlertTriangle className="mr-1 inline" size={14} />{error}</p>}
  </DashboardLayout>;
}
