"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ChevronRight, Filter, Search, UploadCloud } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";

type CandidateRow = { id: string; candidateId: string; name: string; currentTitle: string | null; location: string | null; yearsOfExperience: number; skills: { id: string; name: string }[]; match: { id: string; overallScore: number; recruiterStatus: string; jobTitle: string } | null };
const score = (value: number) => (value <= 1 ? value * 100 : value).toFixed(1);
const statusClass = (status?: string) => status === "SHORTLISTED" ? "tl-status-shortlisted" : status === "REJECTED" ? "tl-status-rejected" : "tl-status-pending";

export default function CandidatesPage() {
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [candidates, setCandidates] = useState<CandidateRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => { const params = new URLSearchParams(); if (search) params.set("search", search); if (status) params.set("status", status); setLoading(true); fetch(`/api/candidates?${params.toString()}`, { signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error("Unable to load candidates."); return response.json() as Promise<CandidateRow[]>; }).then(setCandidates).catch((err: unknown) => { if (err instanceof DOMException && err.name === "AbortError") return; setError(err instanceof Error ? err.message : "Unable to load candidates."); }).finally(() => setLoading(false)); }, 200); return () => { clearTimeout(timer); controller.abort(); }; }, [search, status]);
  return <DashboardLayout><section className="tl-page-intro"><div><p className="tl-eyebrow">03 / CANDIDATES</p><h1 className="tl-heading">A real view of every profile.</h1><p className="tl-subheading">Search the signals that matter, review context without hunting, and keep every recruiter decision traceable.</p></div><Link href="/upload-resume" className="tl-red-button">Import candidate <UploadCloud size={16} /></Link></section><section className="tl-candidate-filter"><label><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, role, or skill" /></label><div><Filter size={15} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All decisions</option><option value="SHORTLISTED">Shortlist</option><option value="PENDING">Pending</option><option value="REJECTED">Reject</option></select></div><span>{candidates.length} profiles</span></section>{error ? <p className="mt-5 border border-[var(--line)] bg-[#fff0ec] p-4 text-sm">{error}</p> : <section className="tl-candidate-directory"><div className="tl-candidate-directory-head"><span>Candidate</span><span>Expertise</span><span>Best match</span><span>Decision</span><span /></div>{loading ? <p className="p-8 text-sm text-[var(--muted)]">Loading candidate directory…</p> : candidates.length ? candidates.map((candidate) => <Link className="tl-candidate-directory-row" href={`/candidates/${candidate.id}`} key={candidate.id}><div className="flex items-center gap-3"><i>{candidate.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</i><span><strong>{candidate.name}</strong><small>{candidate.currentTitle || "Candidate profile"}{candidate.location ? ` · ${candidate.location}` : ""}</small></span></div><div className="flex flex-wrap gap-1">{candidate.skills.slice(0, 2).map((skill) => <em key={skill.id}>{skill.name}</em>)}</div><div><strong>{candidate.match ? score(candidate.match.overallScore) : "—"}</strong><small>{candidate.match?.jobTitle || `${candidate.yearsOfExperience} years experience`}</small></div><span className={`tl-status ${statusClass(candidate.match?.recruiterStatus)}`}>{candidate.match?.recruiterStatus === "SHORTLISTED" ? "Shortlist" : candidate.match?.recruiterStatus === "REJECTED" ? "Reject" : "Pending"}</span><ChevronRight size={18} /></Link>) : <p className="p-8 text-sm text-[var(--muted)]">No candidate profiles match your current filters.</p>}</section>}</DashboardLayout>;
}
