"use client";

import { useRef, useState } from "react";
import { useSession } from "next-auth/react";
import { ArrowRight, BriefcaseBusiness, CheckCircle, FileText, GraduationCap, Sparkles, UploadCloud, X } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";

type Skill = { id: string; name: string; proficiency: string; durationMonths: number };
type Education = { id: string; institution: string; degree: string; fieldOfStudy: string };
type CareerHistory = { id: string; company: string; title: string; durationMonths: number; isCurrent: boolean };
type ParsedCandidate = { id: string; candidateId: string; name: string; headline: string | null; location: string | null; yearsOfExperience: number; skills?: Skill[]; education?: Education[]; careerHistory?: CareerHistory[] };

export default function UploadResumePage() {
  const { data: session } = useSession();
  const role = (session?.user as { role?: string } | undefined)?.role || "recruiter";
  const [file, setFile] = useState<File | null>(null);
  const [dragging, setDragging] = useState(false);
  const [status, setStatus] = useState<"idle" | "uploading" | "success">("idle");
  const [error, setError] = useState<string | null>(null);
  const [candidate, setCandidate] = useState<ParsedCandidate | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const selectFile = (nextFile?: File) => { setError(null); setCandidate(null); setStatus("idle"); if (!nextFile) return; if (nextFile.type !== "application/pdf" && !nextFile.name.toLowerCase().endsWith(".pdf")) { setError("Please choose a PDF resume."); return; } if (nextFile.size > 10 * 1024 * 1024) { setError("The resume must be smaller than 10 MB."); return; } setFile(nextFile); };
  const upload = async () => { if (!file) return; setStatus("uploading"); setError(null); try { const payload = new FormData(); payload.append("file", file); const response = await fetch("/api/candidates/upload", { method: "POST", body: payload }); if (!response.ok) { const message = (await response.json() as { message?: string }).message; throw new Error(message || "Unable to process this resume."); } const result = await response.json() as { data: { id: string } }; const detailResponse = await fetch(`/api/candidates/${result.data.id}`); if (!detailResponse.ok) throw new Error("Resume parsed, but profile details could not be loaded."); setCandidate(await detailResponse.json() as ParsedCandidate); setStatus("success"); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to process this resume."); setStatus("idle"); } };
  const reset = () => { setFile(null); setCandidate(null); setError(null); setStatus("idle"); if (inputRef.current) inputRef.current.value = ""; };

  return <DashboardLayout><section className="tl-page-intro"><div><p className="tl-eyebrow">06 / RESUME UPLOAD</p><h1 className="tl-heading">Bring your work into focus.</h1><p className="tl-subheading">{role === "candidate" ? "Drop in a resume and TalentLens will structure your profile before connecting you to live opportunities." : "Import a candidate resume and convert it into a structured, reviewable profile for the matching workspace."}</p></div></section>
    <section className="tl-upload-layout"><div className="tl-upload-column"><div className={`tl-dropzone ${dragging ? "is-dragging" : ""}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); selectFile(event.dataTransfer.files[0]); }} onClick={() => status === "idle" && inputRef.current?.click()}><input ref={inputRef} type="file" accept="application/pdf" onChange={(event) => selectFile(event.target.files?.[0])} /><UploadCloud size={33} /><strong>{file ? file.name : "Drop your PDF resume here"}</strong><span>{file ? `${Math.max(1, Math.round(file.size / 1024))} KB · ready to parse` : "or select a file from your device"}</span><em>PDF only · maximum 10 MB</em></div>{file && status !== "success" && <div className="mt-3 flex gap-2"><button type="button" className="tl-red-button" disabled={status === "uploading"} onClick={upload}>{status === "uploading" ? "Parsing profile…" : "Parse resume"}<ArrowRight size={16} /></button><button type="button" className="tl-link" onClick={reset}>Clear file</button></div>}{error && <div className="mt-3 flex items-center gap-2 border border-[var(--line)] bg-[#fff0ec] p-3 text-sm"><X size={16} className="text-[var(--coral)]" />{error}</div>}</div><aside className="tl-upload-note"><Sparkles size={19} /><p><strong>Structured, not speculative.</strong> The profile stays tied to the information in the submitted resume and is ready for review before it influences a decision.</p></aside></section>
    {candidate && <section className="tl-parsed-preview"><div className="tl-panel-header"><div><p className="tl-micro">PARSED PROFILE PREVIEW</p><h2 className="tl-panel-title">{candidate.name}</h2></div><span className="tl-status tl-status-shortlisted"><CheckCircle size={13} />Ready to review</span></div><div className="tl-preview-grid"><div><p className="tl-micro">IDENTIFIED EXPERIENCE</p><strong>{candidate.yearsOfExperience.toFixed(1)} years</strong><span>{candidate.headline || "Candidate profile"}</span></div><div><p className="tl-micro">KEY SKILLS</p><div className="flex flex-wrap gap-1.5">{candidate.skills?.slice(0, 5).map((skill) => <span className="tl-skill" key={skill.id}>{skill.name}</span>) || <span className="text-xs text-[var(--muted)]">No structured skills found.</span>}</div></div><div><p className="tl-micro">EDUCATION</p>{candidate.education?.[0] ? <><strong>{candidate.education[0].degree}</strong><span>{candidate.education[0].institution}</span></> : <span>No education record found.</span>}</div></div><div className="tl-data-grid"><article className="tl-panel"><p className="tl-micro">CAREER HISTORY</p><div className="mt-5 space-y-4">{candidate.careerHistory?.slice(0, 3).map((career) => <div className="flex gap-3" key={career.id}><BriefcaseBusiness className="shrink-0 text-[var(--coral)]" size={16} /><div><p className="font-bold text-sm">{career.title}</p><p className="text-xs text-[var(--muted)]">{career.company} · {Math.round(career.durationMonths / 12)} years</p></div></div>) || <p className="text-xs text-[var(--muted)]">No structured career history found.</p>}</div></article><article className="tl-panel"><p className="tl-micro">NEXT STEP</p><div className="mt-5 flex gap-3"><GraduationCap className="shrink-0 text-[var(--coral)]" size={19} /><p className="text-sm leading-6">The original extraction, structured profile, and existing candidate record are now ready for the live matching workflow.</p></div></article></div><button type="button" className="tl-black-button mt-6" onClick={reset}><FileText size={16} />Upload another resume</button></section>}
  </DashboardLayout>;
}
