"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { ArrowRight, BriefcaseBusiness, Check, Eye, FileText, Plus, Trash2, X } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";

type Job = { id: string; title: string; company: string | null; department: string | null; rawDescription: string; experienceYears: number; educationLevel: string; seniority: string; domain: string; createdAt: string };
type FormState = { title: string; company: string; department: string; rawDescription: string; experienceYears: number; educationLevel: string; seniority: string; domain: string };
const emptyForm: FormState = { title: "", company: "", department: "", rawDescription: "", experienceYears: 0, educationLevel: "Bachelor's", seniority: "Mid", domain: "Engineering" };

export default function JobsPage() {
  const { data: session } = useSession();
  const currentUser = session?.user as { id?: string; role?: string } | undefined;
  const isCandidate = currentUser?.role === "candidate";
  const [jobs, setJobs] = useState<Job[]>([]);
  const [applied, setApplied] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Job | null>(null);
  const [form, setForm] = useState<FormState>(emptyForm);
  const [showForm, setShowForm] = useState(false);
  const [showDetails, setShowDetails] = useState(false);
  const [busy, setBusy] = useState(false);

  const loadJobs = async () => { setLoading(true); try { const response = await fetch("/api/jobs"); if (!response.ok) throw new Error("Unable to load jobs."); setJobs(await response.json() as Job[]); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to load jobs."); } finally { setLoading(false); } };
  useEffect(() => { loadJobs(); }, []);
  useEffect(() => { if (!isCandidate) return; fetch("/api/matches").then((response) => response.ok ? response.json() as Promise<{ jobId: string }[]> : []).then((matches) => setApplied(new Set(matches.map((match) => match.jobId)))).catch(() => undefined); }, [isCandidate]);
  const openCreate = () => { setSelected(null); setForm(emptyForm); setShowForm(true); };
  const openEdit = (job: Job) => { setSelected(job); setForm({ title: job.title, company: job.company || "", department: job.department || "", rawDescription: job.rawDescription, experienceYears: job.experienceYears, educationLevel: job.educationLevel, seniority: job.seniority, domain: job.domain }); setShowForm(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (form.rawDescription.trim().length < 20) { setError("Add at least 20 characters of job description text."); return; } setBusy(true); try { const response = await fetch(selected ? `/api/jobs/${selected.id}` : "/api/jobs", { method: selected ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) throw new Error("Unable to save the job."); setShowForm(false); await loadJobs(); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to save the job."); } finally { setBusy(false); } };
  const remove = async (job: Job) => { if (!window.confirm(`Delete ${job.title}? This removes its matching records.`)) return; setBusy(true); try { const response = await fetch(`/api/jobs/${job.id}`, { method: "DELETE" }); if (!response.ok) throw new Error("Unable to delete the job."); await loadJobs(); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to delete the job."); } finally { setBusy(false); } };
  const apply = async (jobId: string) => { setBusy(true); try { const response = await fetch("/api/matches", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jobId }) }); if (!response.ok) throw new Error("Unable to submit this application. Upload a resume first if needed."); setApplied((current) => new Set(current).add(jobId)); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to submit this application."); } finally { setBusy(false); } };

  return <DashboardLayout><section className="tl-page-intro"><div><p className="tl-eyebrow">02 / JOBS</p><h1 className="tl-heading">{isCandidate ? "Open roles, without the noise." : "Every role. One decision surface."}</h1><p className="tl-subheading">{isCandidate ? "Browse the live hiring pipeline and apply with your current profile." : "Turn raw job descriptions into a structured, explainable candidate workflow."}</p></div>{!isCandidate && <button type="button" className="tl-red-button" onClick={openCreate}>Create job <Plus size={16} /></button>}</section>
    {error && <div className="mt-5 flex items-center gap-3 border border-[var(--line)] bg-[#fff0ec] p-4 text-sm">{error}<button onClick={() => setError(null)} className="ml-auto"><X size={17} /></button></div>}
    <section className="tl-job-grid">{loading ? <p className="p-8 text-sm text-[var(--muted)]">Loading job workspace…</p> : jobs.length ? jobs.map((job) => <article className="tl-job-card" key={job.id}><div className="flex items-center justify-between"><span className="tl-status tl-status-shortlisted">{job.seniority || "Open role"}</span><span className="tl-micro">{job.domain || "General"}</span></div><h2>{job.title}</h2><p>{job.company || "TalentLens client"}{job.department ? ` · ${job.department}` : ""}</p><div className="tl-job-metadata"><span><b>{job.experienceYears}</b>years required</span><span><b>{job.educationLevel || "Any"}</b>education</span></div><div className="tl-job-actions">{isCandidate ? <>{applied.has(job.id) ? <span className="tl-status tl-status-shortlisted"><Check size={13} />Applied</span> : <button className="tl-black-button" disabled={busy} onClick={() => apply(job.id)}>Apply <ArrowRight size={15} /></button>}<button className="tl-link" onClick={() => { setSelected(job); setShowDetails(true); }}>Read brief <Eye size={14} /></button></> : <><Link className="tl-black-button" href={`/jobs/${job.id}/evaluate`}>Evaluate <ArrowRight size={15} /></Link><button className="tl-link" onClick={() => openEdit(job)}>Edit</button><button className="tl-link text-[var(--coral)]" disabled={busy} onClick={() => remove(job)}><Trash2 size={14} /></button></>}</div></article>) : <p className="p-8 text-sm text-[var(--muted)]">No active roles yet. Create a job description to start matching candidates.</p>}</section>
    {showForm && <section className="tl-modal-layer" role="dialog" aria-modal="true" aria-label="Create or edit job"><button className="tl-modal-backdrop" onClick={() => setShowForm(false)} aria-label="Close job form" /><article className="tl-modal"><header><div><p className="tl-micro">JOB DESCRIPTION</p><h2>{selected ? "Edit job" : "Create a job from raw text"}</h2></div><button onClick={() => setShowForm(false)} aria-label="Close"><X size={20} /></button></header><form className="tl-form" onSubmit={submit}><label>Job title<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><div className="tl-form-grid"><label>Company<input value={form.company} onChange={(event) => setForm({ ...form, company: event.target.value })} /></label><label>Department<input value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })} /></label></div><label>Raw job description<textarea required value={form.rawDescription} onChange={(event) => setForm({ ...form, rawDescription: event.target.value })} placeholder="Paste the complete role description. TalentLens will retain it as the source for matching." /></label><div className="tl-form-grid"><label>Experience<input type="number" min={0} value={form.experienceYears} onChange={(event) => setForm({ ...form, experienceYears: Number(event.target.value) })} /></label><label>Seniority<select value={form.seniority} onChange={(event) => setForm({ ...form, seniority: event.target.value })}><option>Entry</option><option>Mid</option><option>Senior</option><option>Lead</option></select></label></div><div className="flex justify-end gap-2 border-t border-[var(--line)] pt-4"><button type="button" className="tl-link" onClick={() => setShowForm(false)}>Cancel</button><button type="submit" className="tl-red-button" disabled={busy}>{busy ? "Saving…" : selected ? "Update job" : "Analyze & create"}<ArrowRight size={15} /></button></div></form></article></section>}
    {showDetails && selected && <section className="tl-modal-layer" role="dialog" aria-modal="true" aria-label={`${selected.title} job details`}><button className="tl-modal-backdrop" onClick={() => setShowDetails(false)} aria-label="Close role details" /><article className="tl-modal"><header><div><p className="tl-micro">ROLE BRIEF</p><h2>{selected.title}</h2></div><button onClick={() => setShowDetails(false)} aria-label="Close"><X size={20} /></button></header><div className="tl-modal-body"><section><p className="tl-micro">ROLE CONTEXT</p><p className="mt-2 text-sm">{selected.company || "TalentLens client"} · {selected.department || "Open department"} · {selected.experienceYears} years experience</p></section><section><p className="tl-micro">JOB DESCRIPTION</p><p className="mt-3 whitespace-pre-line text-sm leading-6">{selected.rawDescription}</p></section></div></article></section>}
  </DashboardLayout>;
}
