import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import type { ReactNode } from "react";

export const colors = { ink: "#11110F", paper: "#FFFFFF", muted: "#6E6E68", line: "#161613", soft: "#F3F3EE", red: "#E73525", redSoft: "#FFF0EC", green: "#1A684C", amber: "#9B5D00" };

export function BrandMark() { return <View style={styles.brandMark}><Text style={styles.brandMarkText}>TL</Text></View>; }
export function ScreenTitle({ index, title, description, action }: { index: string; title: string; description: string; action?: ReactNode }) { return <View style={styles.heading}><View><Text style={styles.index}>{index}</Text><Text style={styles.title}>{title}</Text><Text style={styles.description}>{description}</Text></View>{action}</View>; }
export function PrimaryButton({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable onPress={onPress} disabled={disabled} style={({ pressed }) => [styles.primaryButton, (pressed || disabled) && { opacity: disabled ? 0.5 : 0.84, transform: [{ scale: pressed ? 0.97 : 1 }] }]}><Text style={styles.primaryText}>{label}</Text></Pressable>; }
export function StatusPill({ status }: { status: string }) { const value = status === "SHORTLISTED" ? "SHORTLIST" : status === "REJECTED" ? "REJECT" : "PENDING"; const background = value === "SHORTLIST" ? "#E4F3EA" : value === "REJECT" ? "#FDE5E2" : "#FFF2D9"; const color = value === "SHORTLIST" ? colors.green : value === "REJECT" ? colors.red : colors.amber; return <View style={[styles.pill, { backgroundColor: background }]}><Text style={[styles.pillText, { color }]}>{value}</Text></View>; }
export function LoadingState({ label = "Loading TalentLens…" }: { label?: string }) { return <View style={styles.loading}><ActivityIndicator color={colors.red} /><Text style={styles.loadingText}>{label}</Text></View>; }
export function EmptyState({ title, detail }: { title: string; detail: string }) { return <View style={styles.empty}><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyDetail}>{detail}</Text></View>; }

const styles = StyleSheet.create({
  brandMark: { width: 38, height: 38, backgroundColor: colors.red, alignItems: "center", justifyContent: "center" }, brandMarkText: { color: "white", fontWeight: "900", fontSize: 13, letterSpacing: -1 }, heading: { borderBottomWidth: 1, borderColor: colors.line, paddingBottom: 23, gap: 16 }, index: { color: colors.red, fontFamily: "SpaceMono", fontSize: 9, letterSpacing: 1.1 }, title: { color: colors.ink, fontSize: 34, fontWeight: "900", letterSpacing: -2, lineHeight: 34, marginTop: 8 }, description: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 10, maxWidth: 340 }, primaryButton: { backgroundColor: colors.red, borderWidth: 1, borderColor: colors.line, minHeight: 44, alignItems: "center", justifyContent: "center", paddingHorizontal: 16 }, primaryText: { color: "white", fontSize: 12, fontWeight: "800", letterSpacing: 0.2 }, pill: { alignSelf: "flex-start", paddingHorizontal: 7, paddingVertical: 4 }, pillText: { fontFamily: "SpaceMono", fontSize: 9, letterSpacing: 0.5 }, loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, padding: 32 }, loadingText: { color: colors.muted, fontSize: 12 }, empty: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.soft, padding: 20, marginTop: 20 }, emptyTitle: { color: colors.ink, fontWeight: "800", fontSize: 15 }, emptyDetail: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 6 },
});
