"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { getProviders, signIn } from "next-auth/react";
import { AlertCircle, ArrowRight, BriefcaseBusiness, Globe2, GraduationCap, Loader2, Lock, Mail, UserRound } from "lucide-react";

export default function RegisterPage() {
  const router = useRouter();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [role, setRole] = useState<"recruiter" | "candidate">("recruiter");
  const [loading, setLoading] = useState(false);
  const [googleEnabled, setGoogleEnabled] = useState(false);
  const [googleBusy, setGoogleBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; getProviders().then((providers) => { if (active) setGoogleEnabled(Boolean(providers?.google)); }).catch(() => { if (active) setGoogleEnabled(false); }); return () => { active = false; }; }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim() || !email.trim() || !password) { setError("Please fill out every field."); return; } setLoading(true); setError(null); try { const sanitizedEmail = email.trim().toLowerCase(); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email: sanitizedEmail, password, role }) }); const data = await response.json() as { message?: string }; if (!response.ok) throw new Error(data.message || "Registration failed."); const result = await signIn("credentials", { email: sanitizedEmail, password, redirect: false }); if (result?.error) { router.push("/login?registered=true"); return; } router.refresh(); router.push(role === "candidate" ? "/jobs" : "/dashboard"); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to create this account."); } finally { setLoading(false); } };
  const registerGoogle = async () => { setGoogleBusy(true); setError(null); try { const response = await fetch("/api/auth/google-intent", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role }) }); const data = await response.json() as { message?: string }; if (!response.ok) throw new Error(data.message || "Choose a role before continuing."); await signIn("google", { callbackUrl: role === "candidate" ? "/jobs" : "/dashboard" }); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Unable to start Google registration."); setGoogleBusy(false); } };
  return <div className="tl-auth"><aside className="tl-auth-editorial"><p className="tl-eyebrow text-[var(--coral)]">TALENTLENS / CREATE PROFILE</p><h1>Start with an identity, not an inbox.</h1><p>Choose your workspace role and build a structured home for the decisions that follow.</p><div className="tl-auth-square" /><div className="tl-auth-foot"><span>02</span><p>A clear role creates a clearer recruiting workflow.</p></div></aside><main className="tl-auth-form-wrap"><section className="tl-auth-form"><p className="tl-micro">CREATE ACCOUNT</p><h2>Set up your workspace.</h2><p>Start with your identity, then choose how you will use TalentLens.</p><form onSubmit={submit}>{error && <div className="tl-auth-alert"><AlertCircle size={16} />{error}</div>}<div className="tl-register-role"><p>Workspace role</p><div>{(["recruiter", "candidate"] as const).map((option) => { const Icon = option === "recruiter" ? BriefcaseBusiness : GraduationCap; return <button key={option} type="button" className={role === option ? "is-selected" : ""} onClick={() => setRole(option)}><Icon size={16} />{option === "recruiter" ? "Recruiter" : "Candidate"}</button>; })}</div></div><AuthField label="Full name" value={name} onChange={setName} placeholder="Your name" icon={<UserRound size={15} />} /><AuthField label="Email address" type="email" value={email} onChange={setEmail} placeholder="name@company.com" icon={<Mail size={15} />} /><AuthField label="Password" type="password" value={password} onChange={setPassword} placeholder="Minimum 6 characters" icon={<Lock size={15} />} /><button type="submit" className="tl-red-button w-full" disabled={loading}>{loading ? <><Loader2 className="animate-spin" size={16} />Creating account…</> : <>Create account <ArrowRight size={16} /></>}</button></form><div className="tl-auth-divider"><span>or</span></div><button type="button" className="tl-auth-google" onClick={registerGoogle} disabled={!googleEnabled || googleBusy}><Globe2 size={17} />{googleBusy ? "Connecting…" : googleEnabled ? `Continue with Google as ${role === "candidate" ? "Candidate" : "Recruiter"}` : "Google sign-up · setup required"}</button><p className="tl-auth-switch">Already have an account? <Link href="/login">Sign in</Link></p></section></main></div>;
}

function AuthField({ label, type = "text", value, onChange, placeholder, icon }: { label: string; type?: string; value: string; onChange: (value: string) => void; placeholder: string; icon: React.ReactNode }) { return <label>{label}<span>{icon}<input type={type} required value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></span></label>; }
